CREATE TABLE users (
 id UUID PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 display_name VARCHAR(100) NOT NULL, college VARCHAR(160), department VARCHAR(160), profile_image_url TEXT,
 account_status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE','SUSPENDED','PENDING_VERIFICATION')),
 email_verified BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE user_roles (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, role VARCHAR(30) NOT NULL CHECK(role IN ('STUDENT','TEACHER','ADMIN','SUPER_ADMIN')), PRIMARY KEY(user_id,role));
CREATE TABLE refresh_tokens (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash VARCHAR(128) NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);
CREATE TABLE problems (id UUID PRIMARY KEY, author_id UUID NOT NULL REFERENCES users(id), title VARCHAR(200) NOT NULL, slug VARCHAR(220) NOT NULL UNIQUE, description TEXT NOT NULL, input_format TEXT NOT NULL DEFAULT '', output_format TEXT NOT NULL DEFAULT '', constraints_text TEXT NOT NULL DEFAULT '', difficulty VARCHAR(30) NOT NULL CHECK(difficulty IN ('EASY','MEDIUM','HARD')), time_limit_ms INTEGER NOT NULL CHECK(time_limit_ms BETWEEN 100 AND 60000), memory_limit_mb INTEGER NOT NULL CHECK(memory_limit_mb BETWEEN 16 AND 4096), maximum_score INTEGER NOT NULL CHECK(maximum_score > 0), published BOOLEAN NOT NULL DEFAULT FALSE, version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_problems_published_difficulty ON problems(published,difficulty,created_at DESC);
CREATE TABLE tags (id UUID PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, slug VARCHAR(90) NOT NULL UNIQUE);
CREATE TABLE problem_tags (problem_id UUID NOT NULL REFERENCES problems(id) ON DELETE CASCADE, tag_id UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(problem_id,tag_id));
CREATE TABLE problem_supported_languages (problem_id UUID NOT NULL REFERENCES problems(id) ON DELETE CASCADE, language VARCHAR(32) NOT NULL, PRIMARY KEY(problem_id,language));
CREATE TABLE test_cases (id UUID PRIMARY KEY, problem_id UUID NOT NULL REFERENCES problems(id) ON DELETE CASCADE, input_data TEXT NOT NULL, expected_output TEXT NOT NULL, hidden BOOLEAN NOT NULL DEFAULT TRUE, weight INTEGER NOT NULL DEFAULT 1 CHECK(weight > 0), case_kind VARCHAR(24) NOT NULL DEFAULT 'STANDARD' CHECK(case_kind IN ('STANDARD','EDGE','LARGE')), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_test_cases_problem ON test_cases(problem_id);
CREATE TABLE contests (id UUID PRIMARY KEY, created_by UUID NOT NULL REFERENCES users(id), name VARCHAR(200) NOT NULL, description TEXT NOT NULL DEFAULT '', starts_at TIMESTAMPTZ NOT NULL, ends_at TIMESTAMPTZ NOT NULL, registration_deadline TIMESTAMPTZ NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SCHEDULED','ACTIVE','ENDED','RESULT_PUBLISHED')), maximum_participants INTEGER CHECK(maximum_participants > 0), visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC' CHECK(visibility IN ('PUBLIC','PRIVATE')), access_code_hash VARCHAR(128), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK(ends_at > starts_at), CHECK(registration_deadline <= starts_at));
CREATE INDEX idx_contests_schedule ON contests(status,starts_at);
CREATE TABLE contest_problems (contest_id UUID NOT NULL REFERENCES contests(id) ON DELETE CASCADE, problem_id UUID NOT NULL REFERENCES problems(id), problem_order INTEGER NOT NULL CHECK(problem_order > 0), maximum_score INTEGER NOT NULL CHECK(maximum_score > 0), PRIMARY KEY(contest_id,problem_id), UNIQUE(contest_id,problem_order));
CREATE TABLE contest_participants (contest_id UUID NOT NULL REFERENCES contests(id) ON DELETE CASCADE, student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, registered_at TIMESTAMPTZ NOT NULL DEFAULT now(), participation_status VARCHAR(20) NOT NULL DEFAULT 'REGISTERED' CHECK(participation_status IN ('REGISTERED','ACTIVE','COMPLETED','DISQUALIFICATION_REVIEW')), final_score INTEGER NOT NULL DEFAULT 0, final_rank INTEGER, PRIMARY KEY(contest_id,student_id));
CREATE INDEX idx_participants_rank ON contest_participants(contest_id,final_score DESC,registered_at);
CREATE TABLE submissions (id UUID PRIMARY KEY, student_id UUID NOT NULL REFERENCES users(id), problem_id UUID NOT NULL REFERENCES problems(id), contest_id UUID REFERENCES contests(id), language VARCHAR(32) NOT NULL, source_code TEXT NOT NULL, status VARCHAR(32) NOT NULL CHECK(status IN ('CREATED','QUEUED','PROCESSING','COMPILING','RUNNING','EVALUATING','COMPLETED')), verdict VARCHAR(40) NOT NULL DEFAULT 'PENDING' CHECK(verdict IN ('PENDING','ACCEPTED','WRONG_ANSWER','COMPILATION_ERROR','RUNTIME_ERROR','TIME_LIMIT_EXCEEDED','MEMORY_LIMIT_EXCEEDED','SYSTEM_ERROR')), execution_time_ms BIGINT, memory_usage_kb BIGINT, score INTEGER NOT NULL DEFAULT 0, submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(), completed_at TIMESTAMPTZ, version BIGINT NOT NULL DEFAULT 0);
CREATE INDEX idx_submission_student_created ON submissions(student_id,submitted_at DESC); CREATE INDEX idx_submission_problem ON submissions(problem_id,submitted_at DESC); CREATE INDEX idx_submission_contest ON submissions(contest_id,submitted_at DESC); CREATE INDEX idx_submission_status ON submissions(status,submitted_at); CREATE INDEX idx_submission_recent ON submissions(submitted_at DESC);
CREATE TABLE submission_results (submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE, test_case_id UUID NOT NULL REFERENCES test_cases(id), result VARCHAR(40) NOT NULL, execution_time_ms BIGINT, memory_usage_kb BIGINT, PRIMARY KEY(submission_id,test_case_id));
CREATE TABLE notifications (id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, type VARCHAR(32) NOT NULL, title VARCHAR(200) NOT NULL, message TEXT NOT NULL, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_notification_user_created ON notifications(user_id,created_at DESC);
CREATE TABLE audit_logs (id UUID PRIMARY KEY, user_id UUID REFERENCES users(id) ON DELETE SET NULL, action VARCHAR(80) NOT NULL, resource_type VARCHAR(80) NOT NULL, resource_id VARCHAR(100), ip_address INET, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_audit_user_created ON audit_logs(user_id,created_at DESC); CREATE INDEX idx_audit_resource ON audit_logs(resource_type,resource_id,created_at DESC);
CREATE TABLE suspicious_activity (id UUID PRIMARY KEY, student_id UUID NOT NULL REFERENCES users(id), contest_id UUID REFERENCES contests(id), activity_type VARCHAR(80) NOT NULL, suspicion_score NUMERIC(5,2) NOT NULL CHECK(suspicion_score BETWEEN 0 AND 100), evidence_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, review_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(review_status IN ('PENDING','IN_REVIEW','CLEARED','CONFIRMED')), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX idx_suspicious_review ON suspicious_activity(review_status,created_at DESC);
CREATE TABLE ai_code_reviews (submission_id UUID PRIMARY KEY REFERENCES submissions(id) ON DELETE CASCADE, code_quality_feedback TEXT, time_complexity VARCHAR(255), space_complexity VARCHAR(255), suggestions JSONB NOT NULL DEFAULT '[]'::jsonb, potential_issues JSONB NOT NULL DEFAULT '[]'::jsonb, generated_at TIMESTAMPTZ NOT NULL DEFAULT now());
